import Head from "next/head";
import Header from "./components/header";
import Footer from "./components/footer";
import ProductView from "./components/views/productview";

export default function Home() {
  return (
    <>
      <div className="bg-white">
        <Head>
          <title>BASTAH961</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <ProductView />
        <Footer />
      </div>
    </>
  );
}
